name: Docker Build and Push

on:
  push:
    branches:
    - master
    - action

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build main.go
      
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          jwmtp2/drone-plugin-regex:latest
